/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as ConsumidorIndexRouteImport } from './routes/consumidor/index'
import { Route as ConsumidorCarritoRouteImport } from './routes/consumidor/carrito'
import { Route as ConsumidorCheckoutRouteImport } from './routes/consumidor/checkout'
import { Route as ConsumidorCosechaRouteImport } from './routes/consumidor/cosecha'
import { Route as ConsumidorNotificacionesRouteImport } from './routes/consumidor/notificaciones'
import { Route as ConsumidorPedidosRouteImport } from './routes/consumidor/pedidos'
import { Route as ConsumidorPerfilRouteImport } from './routes/consumidor/perfil'
import { Route as ConsumidorProductoresRouteImport } from './routes/consumidor/productores'
import { Route as ConsumidorRecibirRouteImport } from './routes/consumidor/recibir'
import { Route as DistribuidorIndexRouteImport } from './routes/distribuidor/index'
import { Route as DistribuidorAnalyticsRouteImport } from './routes/distribuidor/analytics'
import { Route as DistribuidorCatalogoRouteImport } from './routes/distribuidor/catalogo'
import { Route as DistribuidorFinanzasRouteImport } from './routes/distribuidor/finanzas'
import { Route as DistribuidorNotificacionesRouteImport } from './routes/distribuidor/notificaciones'
import { Route as DistribuidorPerfilRouteImport } from './routes/distribuidor/perfil'
import { Route as DistribuidorRutaRouteImport } from './routes/distribuidor/ruta'
import { Route as DistribuidorTrazabilidadRouteImport } from './routes/distribuidor/trazabilidad'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginRolRouteImport } from './routes/login.rol'
import { Route as LoteIdRouteImport } from './routes/lote.$id'
import { Route as ProductorIndexRouteImport } from './routes/productor/index'
import { Route as ProductorCatalogoRouteImport } from './routes/productor/catalogo'
import { Route as ProductorFinanzasRouteImport } from './routes/productor/finanzas'
import { Route as ProductorNotificacionesRouteImport } from './routes/productor/notificaciones'
import { Route as ProductorPedidosRouteImport } from './routes/productor/pedidos'
import { Route as ProductorPerfilRouteImport } from './routes/productor/perfil'
import { Route as ProductorTransparenciaRouteImport } from './routes/productor/transparencia'
import { Route as ConsumidorProductoIdRouteImport } from './routes/consumidor/producto.$id'
import { Route as ConsumidorProductorSlugRouteImport } from './routes/consumidor/productor.$slug'
import { Route as DistribuidorEntregaIdRouteImport } from './routes/distribuidor/entrega.$id'
import { Route as DistribuidorRecoleccionKeyRouteImport } from './routes/distribuidor/recoleccion.$key'
import { Route as ProductorPedidoIdRouteImport } from './routes/productor/pedido.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumidorIndexRoute = ConsumidorIndexRouteImport.update({
  id: '/consumidor/',
  path: '/consumidor/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumidorCarritoRoute = ConsumidorCarritoRouteImport.update({
  id: '/consumidor/carrito',
  path: '/consumidor/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumidorCheckoutRoute = ConsumidorCheckoutRouteImport.update({
  id: '/consumidor/checkout',
  path: '/consumidor/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumidorCosechaRoute = ConsumidorCosechaRouteImport.update({
  id: '/consumidor/cosecha',
  path: '/consumidor/cosecha',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumidorNotificacionesRoute =
  ConsumidorNotificacionesRouteImport.update({
    id: '/consumidor/notificaciones',
    path: '/consumidor/notificaciones',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConsumidorPedidosRoute = ConsumidorPedidosRouteImport.update({
  id: '/consumidor/pedidos',
  path: '/consumidor/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumidorPerfilRoute = ConsumidorPerfilRouteImport.update({
  id: '/consumidor/perfil',
  path: '/consumidor/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumidorProductoresRoute = ConsumidorProductoresRouteImport.update({
  id: '/consumidor/productores',
  path: '/consumidor/productores',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumidorRecibirRoute = ConsumidorRecibirRouteImport.update({
  id: '/consumidor/recibir',
  path: '/consumidor/recibir',
  getParentRoute: () => rootRouteImport,
} as any)
const DistribuidorIndexRoute = DistribuidorIndexRouteImport.update({
  id: '/distribuidor/',
  path: '/distribuidor/',
  getParentRoute: () => rootRouteImport,
} as any)
const DistribuidorAnalyticsRoute = DistribuidorAnalyticsRouteImport.update({
  id: '/distribuidor/analytics',
  path: '/distribuidor/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DistribuidorCatalogoRoute = DistribuidorCatalogoRouteImport.update({
  id: '/distribuidor/catalogo',
  path: '/distribuidor/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const DistribuidorFinanzasRoute = DistribuidorFinanzasRouteImport.update({
  id: '/distribuidor/finanzas',
  path: '/distribuidor/finanzas',
  getParentRoute: () => rootRouteImport,
} as any)
const DistribuidorNotificacionesRoute =
  DistribuidorNotificacionesRouteImport.update({
    id: '/distribuidor/notificaciones',
    path: '/distribuidor/notificaciones',
    getParentRoute: () => rootRouteImport,
  } as any)
const DistribuidorPerfilRoute = DistribuidorPerfilRouteImport.update({
  id: '/distribuidor/perfil',
  path: '/distribuidor/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const DistribuidorRutaRoute = DistribuidorRutaRouteImport.update({
  id: '/distribuidor/ruta',
  path: '/distribuidor/ruta',
  getParentRoute: () => rootRouteImport,
} as any)
const DistribuidorTrazabilidadRoute =
  DistribuidorTrazabilidadRouteImport.update({
    id: '/distribuidor/trazabilidad',
    path: '/distribuidor/trazabilidad',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRolRoute = LoginRolRouteImport.update({
  id: '/login/rol',
  path: '/login/rol',
  getParentRoute: () => rootRouteImport,
} as any)
const LoteIdRoute = LoteIdRouteImport.update({
  id: '/lote/$id',
  path: '/lote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductorIndexRoute = ProductorIndexRouteImport.update({
  id: '/productor/',
  path: '/productor/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductorCatalogoRoute = ProductorCatalogoRouteImport.update({
  id: '/productor/catalogo',
  path: '/productor/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductorFinanzasRoute = ProductorFinanzasRouteImport.update({
  id: '/productor/finanzas',
  path: '/productor/finanzas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductorNotificacionesRoute = ProductorNotificacionesRouteImport.update({
  id: '/productor/notificaciones',
  path: '/productor/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductorPedidosRoute = ProductorPedidosRouteImport.update({
  id: '/productor/pedidos',
  path: '/productor/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductorPerfilRoute = ProductorPerfilRouteImport.update({
  id: '/productor/perfil',
  path: '/productor/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductorTransparenciaRoute = ProductorTransparenciaRouteImport.update({
  id: '/productor/transparencia',
  path: '/productor/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumidorProductoIdRoute = ConsumidorProductoIdRouteImport.update({
  id: '/consumidor/producto/$id',
  path: '/consumidor/producto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumidorProductorSlugRoute = ConsumidorProductorSlugRouteImport.update({
  id: '/consumidor/productor/$slug',
  path: '/consumidor/productor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DistribuidorEntregaIdRoute = DistribuidorEntregaIdRouteImport.update({
  id: '/distribuidor/entrega/$id',
  path: '/distribuidor/entrega/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DistribuidorRecoleccionKeyRoute =
  DistribuidorRecoleccionKeyRouteImport.update({
    id: '/distribuidor/recoleccion/$key',
    path: '/distribuidor/recoleccion/$key',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductorPedidoIdRoute = ProductorPedidoIdRouteImport.update({
  id: '/productor/pedido/$id',
  path: '/productor/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/registro': typeof RegistroRoute
  '/consumidor/carrito': typeof ConsumidorCarritoRoute
  '/consumidor/checkout': typeof ConsumidorCheckoutRoute
  '/consumidor/cosecha': typeof ConsumidorCosechaRoute
  '/consumidor/notificaciones': typeof ConsumidorNotificacionesRoute
  '/consumidor/pedidos': typeof ConsumidorPedidosRoute
  '/consumidor/perfil': typeof ConsumidorPerfilRoute
  '/consumidor/productores': typeof ConsumidorProductoresRoute
  '/consumidor/recibir': typeof ConsumidorRecibirRoute
  '/distribuidor/analytics': typeof DistribuidorAnalyticsRoute
  '/distribuidor/catalogo': typeof DistribuidorCatalogoRoute
  '/distribuidor/finanzas': typeof DistribuidorFinanzasRoute
  '/distribuidor/notificaciones': typeof DistribuidorNotificacionesRoute
  '/distribuidor/perfil': typeof DistribuidorPerfilRoute
  '/distribuidor/ruta': typeof DistribuidorRutaRoute
  '/distribuidor/trazabilidad': typeof DistribuidorTrazabilidadRoute
  '/login/rol': typeof LoginRolRoute
  '/lote/$id': typeof LoteIdRoute
  '/productor/catalogo': typeof ProductorCatalogoRoute
  '/productor/finanzas': typeof ProductorFinanzasRoute
  '/productor/notificaciones': typeof ProductorNotificacionesRoute
  '/productor/pedidos': typeof ProductorPedidosRoute
  '/productor/perfil': typeof ProductorPerfilRoute
  '/productor/transparencia': typeof ProductorTransparenciaRoute
  '/consumidor/': typeof ConsumidorIndexRoute
  '/distribuidor/': typeof DistribuidorIndexRoute
  '/login/': typeof LoginIndexRoute
  '/productor/': typeof ProductorIndexRoute
  '/consumidor/producto/$id': typeof ConsumidorProductoIdRoute
  '/consumidor/productor/$slug': typeof ConsumidorProductorSlugRoute
  '/distribuidor/entrega/$id': typeof DistribuidorEntregaIdRoute
  '/distribuidor/recoleccion/$key': typeof DistribuidorRecoleccionKeyRoute
  '/productor/pedido/$id': typeof ProductorPedidoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/registro': typeof RegistroRoute
  '/consumidor/carrito': typeof ConsumidorCarritoRoute
  '/consumidor/checkout': typeof ConsumidorCheckoutRoute
  '/consumidor/cosecha': typeof ConsumidorCosechaRoute
  '/consumidor/notificaciones': typeof ConsumidorNotificacionesRoute
  '/consumidor/pedidos': typeof ConsumidorPedidosRoute
  '/consumidor/perfil': typeof ConsumidorPerfilRoute
  '/consumidor/productores': typeof ConsumidorProductoresRoute
  '/consumidor/recibir': typeof ConsumidorRecibirRoute
  '/distribuidor/analytics': typeof DistribuidorAnalyticsRoute
  '/distribuidor/catalogo': typeof DistribuidorCatalogoRoute
  '/distribuidor/finanzas': typeof DistribuidorFinanzasRoute
  '/distribuidor/notificaciones': typeof DistribuidorNotificacionesRoute
  '/distribuidor/perfil': typeof DistribuidorPerfilRoute
  '/distribuidor/ruta': typeof DistribuidorRutaRoute
  '/distribuidor/trazabilidad': typeof DistribuidorTrazabilidadRoute
  '/login/rol': typeof LoginRolRoute
  '/lote/$id': typeof LoteIdRoute
  '/productor/catalogo': typeof ProductorCatalogoRoute
  '/productor/finanzas': typeof ProductorFinanzasRoute
  '/productor/notificaciones': typeof ProductorNotificacionesRoute
  '/productor/pedidos': typeof ProductorPedidosRoute
  '/productor/perfil': typeof ProductorPerfilRoute
  '/productor/transparencia': typeof ProductorTransparenciaRoute
  '/consumidor': typeof ConsumidorIndexRoute
  '/distribuidor': typeof DistribuidorIndexRoute
  '/login': typeof LoginIndexRoute
  '/productor': typeof ProductorIndexRoute
  '/consumidor/producto/$id': typeof ConsumidorProductoIdRoute
  '/consumidor/productor/$slug': typeof ConsumidorProductorSlugRoute
  '/distribuidor/entrega/$id': typeof DistribuidorEntregaIdRoute
  '/distribuidor/recoleccion/$key': typeof DistribuidorRecoleccionKeyRoute
  '/productor/pedido/$id': typeof ProductorPedidoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/registro': typeof RegistroRoute
  '/consumidor/carrito': typeof ConsumidorCarritoRoute
  '/consumidor/checkout': typeof ConsumidorCheckoutRoute
  '/consumidor/cosecha': typeof ConsumidorCosechaRoute
  '/consumidor/notificaciones': typeof ConsumidorNotificacionesRoute
  '/consumidor/pedidos': typeof ConsumidorPedidosRoute
  '/consumidor/perfil': typeof ConsumidorPerfilRoute
  '/consumidor/productores': typeof ConsumidorProductoresRoute
  '/consumidor/recibir': typeof ConsumidorRecibirRoute
  '/distribuidor/analytics': typeof DistribuidorAnalyticsRoute
  '/distribuidor/catalogo': typeof DistribuidorCatalogoRoute
  '/distribuidor/finanzas': typeof DistribuidorFinanzasRoute
  '/distribuidor/notificaciones': typeof DistribuidorNotificacionesRoute
  '/distribuidor/perfil': typeof DistribuidorPerfilRoute
  '/distribuidor/ruta': typeof DistribuidorRutaRoute
  '/distribuidor/trazabilidad': typeof DistribuidorTrazabilidadRoute
  '/login/rol': typeof LoginRolRoute
  '/lote/$id': typeof LoteIdRoute
  '/productor/catalogo': typeof ProductorCatalogoRoute
  '/productor/finanzas': typeof ProductorFinanzasRoute
  '/productor/notificaciones': typeof ProductorNotificacionesRoute
  '/productor/pedidos': typeof ProductorPedidosRoute
  '/productor/perfil': typeof ProductorPerfilRoute
  '/productor/transparencia': typeof ProductorTransparenciaRoute
  '/consumidor/': typeof ConsumidorIndexRoute
  '/distribuidor/': typeof DistribuidorIndexRoute
  '/login/': typeof LoginIndexRoute
  '/productor/': typeof ProductorIndexRoute
  '/consumidor/producto/$id': typeof ConsumidorProductoIdRoute
  '/consumidor/productor/$slug': typeof ConsumidorProductorSlugRoute
  '/distribuidor/entrega/$id': typeof DistribuidorEntregaIdRoute
  '/distribuidor/recoleccion/$key': typeof DistribuidorRecoleccionKeyRoute
  '/productor/pedido/$id': typeof ProductorPedidoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/registro'
    | '/consumidor/carrito'
    | '/consumidor/checkout'
    | '/consumidor/cosecha'
    | '/consumidor/notificaciones'
    | '/consumidor/pedidos'
    | '/consumidor/perfil'
    | '/consumidor/productores'
    | '/consumidor/recibir'
    | '/distribuidor/analytics'
    | '/distribuidor/catalogo'
    | '/distribuidor/finanzas'
    | '/distribuidor/notificaciones'
    | '/distribuidor/perfil'
    | '/distribuidor/ruta'
    | '/distribuidor/trazabilidad'
    | '/login/rol'
    | '/lote/$id'
    | '/productor/catalogo'
    | '/productor/finanzas'
    | '/productor/notificaciones'
    | '/productor/pedidos'
    | '/productor/perfil'
    | '/productor/transparencia'
    | '/consumidor/'
    | '/distribuidor/'
    | '/login/'
    | '/productor/'
    | '/consumidor/producto/$id'
    | '/consumidor/productor/$slug'
    | '/distribuidor/entrega/$id'
    | '/distribuidor/recoleccion/$key'
    | '/productor/pedido/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/registro'
    | '/consumidor/carrito'
    | '/consumidor/checkout'
    | '/consumidor/cosecha'
    | '/consumidor/notificaciones'
    | '/consumidor/pedidos'
    | '/consumidor/perfil'
    | '/consumidor/productores'
    | '/consumidor/recibir'
    | '/distribuidor/analytics'
    | '/distribuidor/catalogo'
    | '/distribuidor/finanzas'
    | '/distribuidor/notificaciones'
    | '/distribuidor/perfil'
    | '/distribuidor/ruta'
    | '/distribuidor/trazabilidad'
    | '/login/rol'
    | '/lote/$id'
    | '/productor/catalogo'
    | '/productor/finanzas'
    | '/productor/notificaciones'
    | '/productor/pedidos'
    | '/productor/perfil'
    | '/productor/transparencia'
    | '/consumidor'
    | '/distribuidor'
    | '/login'
    | '/productor'
    | '/consumidor/producto/$id'
    | '/consumidor/productor/$slug'
    | '/distribuidor/entrega/$id'
    | '/distribuidor/recoleccion/$key'
    | '/productor/pedido/$id'
  id:
    | '__root__'
    | '/'
    | '/registro'
    | '/consumidor/carrito'
    | '/consumidor/checkout'
    | '/consumidor/cosecha'
    | '/consumidor/notificaciones'
    | '/consumidor/pedidos'
    | '/consumidor/perfil'
    | '/consumidor/productores'
    | '/consumidor/recibir'
    | '/distribuidor/analytics'
    | '/distribuidor/catalogo'
    | '/distribuidor/finanzas'
    | '/distribuidor/notificaciones'
    | '/distribuidor/perfil'
    | '/distribuidor/ruta'
    | '/distribuidor/trazabilidad'
    | '/login/rol'
    | '/lote/$id'
    | '/productor/catalogo'
    | '/productor/finanzas'
    | '/productor/notificaciones'
    | '/productor/pedidos'
    | '/productor/perfil'
    | '/productor/transparencia'
    | '/consumidor/'
    | '/distribuidor/'
    | '/login/'
    | '/productor/'
    | '/consumidor/producto/$id'
    | '/consumidor/productor/$slug'
    | '/distribuidor/entrega/$id'
    | '/distribuidor/recoleccion/$key'
    | '/productor/pedido/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegistroRoute: typeof RegistroRoute
  ConsumidorCarritoRoute: typeof ConsumidorCarritoRoute
  ConsumidorCheckoutRoute: typeof ConsumidorCheckoutRoute
  ConsumidorCosechaRoute: typeof ConsumidorCosechaRoute
  ConsumidorNotificacionesRoute: typeof ConsumidorNotificacionesRoute
  ConsumidorPedidosRoute: typeof ConsumidorPedidosRoute
  ConsumidorPerfilRoute: typeof ConsumidorPerfilRoute
  ConsumidorProductoresRoute: typeof ConsumidorProductoresRoute
  ConsumidorRecibirRoute: typeof ConsumidorRecibirRoute
  DistribuidorAnalyticsRoute: typeof DistribuidorAnalyticsRoute
  DistribuidorCatalogoRoute: typeof DistribuidorCatalogoRoute
  DistribuidorFinanzasRoute: typeof DistribuidorFinanzasRoute
  DistribuidorNotificacionesRoute: typeof DistribuidorNotificacionesRoute
  DistribuidorPerfilRoute: typeof DistribuidorPerfilRoute
  DistribuidorRutaRoute: typeof DistribuidorRutaRoute
  DistribuidorTrazabilidadRoute: typeof DistribuidorTrazabilidadRoute
  LoginRolRoute: typeof LoginRolRoute
  LoteIdRoute: typeof LoteIdRoute
  ProductorCatalogoRoute: typeof ProductorCatalogoRoute
  ProductorFinanzasRoute: typeof ProductorFinanzasRoute
  ProductorNotificacionesRoute: typeof ProductorNotificacionesRoute
  ProductorPedidosRoute: typeof ProductorPedidosRoute
  ProductorPerfilRoute: typeof ProductorPerfilRoute
  ProductorTransparenciaRoute: typeof ProductorTransparenciaRoute
  ConsumidorIndexRoute: typeof ConsumidorIndexRoute
  DistribuidorIndexRoute: typeof DistribuidorIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProductorIndexRoute: typeof ProductorIndexRoute
  ConsumidorProductoIdRoute: typeof ConsumidorProductoIdRoute
  ConsumidorProductorSlugRoute: typeof ConsumidorProductorSlugRoute
  DistribuidorEntregaIdRoute: typeof DistribuidorEntregaIdRoute
  DistribuidorRecoleccionKeyRoute: typeof DistribuidorRecoleccionKeyRoute
  ProductorPedidoIdRoute: typeof ProductorPedidoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumidor/': {
      id: '/consumidor/'
      path: '/consumidor'
      fullPath: '/consumidor/'
      preLoaderRoute: typeof ConsumidorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumidor/carrito': {
      id: '/consumidor/carrito'
      path: '/consumidor/carrito'
      fullPath: '/consumidor/carrito'
      preLoaderRoute: typeof ConsumidorCarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumidor/checkout': {
      id: '/consumidor/checkout'
      path: '/consumidor/checkout'
      fullPath: '/consumidor/checkout'
      preLoaderRoute: typeof ConsumidorCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumidor/cosecha': {
      id: '/consumidor/cosecha'
      path: '/consumidor/cosecha'
      fullPath: '/consumidor/cosecha'
      preLoaderRoute: typeof ConsumidorCosechaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumidor/notificaciones': {
      id: '/consumidor/notificaciones'
      path: '/consumidor/notificaciones'
      fullPath: '/consumidor/notificaciones'
      preLoaderRoute: typeof ConsumidorNotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumidor/pedidos': {
      id: '/consumidor/pedidos'
      path: '/consumidor/pedidos'
      fullPath: '/consumidor/pedidos'
      preLoaderRoute: typeof ConsumidorPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumidor/perfil': {
      id: '/consumidor/perfil'
      path: '/consumidor/perfil'
      fullPath: '/consumidor/perfil'
      preLoaderRoute: typeof ConsumidorPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumidor/productores': {
      id: '/consumidor/productores'
      path: '/consumidor/productores'
      fullPath: '/consumidor/productores'
      preLoaderRoute: typeof ConsumidorProductoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumidor/recibir': {
      id: '/consumidor/recibir'
      path: '/consumidor/recibir'
      fullPath: '/consumidor/recibir'
      preLoaderRoute: typeof ConsumidorRecibirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribuidor/': {
      id: '/distribuidor/'
      path: '/distribuidor'
      fullPath: '/distribuidor/'
      preLoaderRoute: typeof DistribuidorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribuidor/analytics': {
      id: '/distribuidor/analytics'
      path: '/distribuidor/analytics'
      fullPath: '/distribuidor/analytics'
      preLoaderRoute: typeof DistribuidorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribuidor/catalogo': {
      id: '/distribuidor/catalogo'
      path: '/distribuidor/catalogo'
      fullPath: '/distribuidor/catalogo'
      preLoaderRoute: typeof DistribuidorCatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribuidor/finanzas': {
      id: '/distribuidor/finanzas'
      path: '/distribuidor/finanzas'
      fullPath: '/distribuidor/finanzas'
      preLoaderRoute: typeof DistribuidorFinanzasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribuidor/notificaciones': {
      id: '/distribuidor/notificaciones'
      path: '/distribuidor/notificaciones'
      fullPath: '/distribuidor/notificaciones'
      preLoaderRoute: typeof DistribuidorNotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribuidor/perfil': {
      id: '/distribuidor/perfil'
      path: '/distribuidor/perfil'
      fullPath: '/distribuidor/perfil'
      preLoaderRoute: typeof DistribuidorPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribuidor/ruta': {
      id: '/distribuidor/ruta'
      path: '/distribuidor/ruta'
      fullPath: '/distribuidor/ruta'
      preLoaderRoute: typeof DistribuidorRutaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribuidor/trazabilidad': {
      id: '/distribuidor/trazabilidad'
      path: '/distribuidor/trazabilidad'
      fullPath: '/distribuidor/trazabilidad'
      preLoaderRoute: typeof DistribuidorTrazabilidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/rol': {
      id: '/login/rol'
      path: '/login/rol'
      fullPath: '/login/rol'
      preLoaderRoute: typeof LoginRolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lote/$id': {
      id: '/lote/$id'
      path: '/lote/$id'
      fullPath: '/lote/$id'
      preLoaderRoute: typeof LoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productor/': {
      id: '/productor/'
      path: '/productor'
      fullPath: '/productor/'
      preLoaderRoute: typeof ProductorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productor/catalogo': {
      id: '/productor/catalogo'
      path: '/productor/catalogo'
      fullPath: '/productor/catalogo'
      preLoaderRoute: typeof ProductorCatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productor/finanzas': {
      id: '/productor/finanzas'
      path: '/productor/finanzas'
      fullPath: '/productor/finanzas'
      preLoaderRoute: typeof ProductorFinanzasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productor/notificaciones': {
      id: '/productor/notificaciones'
      path: '/productor/notificaciones'
      fullPath: '/productor/notificaciones'
      preLoaderRoute: typeof ProductorNotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productor/pedidos': {
      id: '/productor/pedidos'
      path: '/productor/pedidos'
      fullPath: '/productor/pedidos'
      preLoaderRoute: typeof ProductorPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productor/perfil': {
      id: '/productor/perfil'
      path: '/productor/perfil'
      fullPath: '/productor/perfil'
      preLoaderRoute: typeof ProductorPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productor/transparencia': {
      id: '/productor/transparencia'
      path: '/productor/transparencia'
      fullPath: '/productor/transparencia'
      preLoaderRoute: typeof ProductorTransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumidor/producto/$id': {
      id: '/consumidor/producto/$id'
      path: '/consumidor/producto/$id'
      fullPath: '/consumidor/producto/$id'
      preLoaderRoute: typeof ConsumidorProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumidor/productor/$slug': {
      id: '/consumidor/productor/$slug'
      path: '/consumidor/productor/$slug'
      fullPath: '/consumidor/productor/$slug'
      preLoaderRoute: typeof ConsumidorProductorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribuidor/entrega/$id': {
      id: '/distribuidor/entrega/$id'
      path: '/distribuidor/entrega/$id'
      fullPath: '/distribuidor/entrega/$id'
      preLoaderRoute: typeof DistribuidorEntregaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribuidor/recoleccion/$key': {
      id: '/distribuidor/recoleccion/$key'
      path: '/distribuidor/recoleccion/$key'
      fullPath: '/distribuidor/recoleccion/$key'
      preLoaderRoute: typeof DistribuidorRecoleccionKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productor/pedido/$id': {
      id: '/productor/pedido/$id'
      path: '/productor/pedido/$id'
      fullPath: '/productor/pedido/$id'
      preLoaderRoute: typeof ProductorPedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegistroRoute: RegistroRoute,
  ConsumidorCarritoRoute: ConsumidorCarritoRoute,
  ConsumidorCheckoutRoute: ConsumidorCheckoutRoute,
  ConsumidorCosechaRoute: ConsumidorCosechaRoute,
  ConsumidorNotificacionesRoute: ConsumidorNotificacionesRoute,
  ConsumidorPedidosRoute: ConsumidorPedidosRoute,
  ConsumidorPerfilRoute: ConsumidorPerfilRoute,
  ConsumidorProductoresRoute: ConsumidorProductoresRoute,
  ConsumidorRecibirRoute: ConsumidorRecibirRoute,
  DistribuidorAnalyticsRoute: DistribuidorAnalyticsRoute,
  DistribuidorCatalogoRoute: DistribuidorCatalogoRoute,
  DistribuidorFinanzasRoute: DistribuidorFinanzasRoute,
  DistribuidorNotificacionesRoute: DistribuidorNotificacionesRoute,
  DistribuidorPerfilRoute: DistribuidorPerfilRoute,
  DistribuidorRutaRoute: DistribuidorRutaRoute,
  DistribuidorTrazabilidadRoute: DistribuidorTrazabilidadRoute,
  LoginRolRoute: LoginRolRoute,
  LoteIdRoute: LoteIdRoute,
  ProductorCatalogoRoute: ProductorCatalogoRoute,
  ProductorFinanzasRoute: ProductorFinanzasRoute,
  ProductorNotificacionesRoute: ProductorNotificacionesRoute,
  ProductorPedidosRoute: ProductorPedidosRoute,
  ProductorPerfilRoute: ProductorPerfilRoute,
  ProductorTransparenciaRoute: ProductorTransparenciaRoute,
  ConsumidorIndexRoute: ConsumidorIndexRoute,
  DistribuidorIndexRoute: DistribuidorIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProductorIndexRoute: ProductorIndexRoute,
  ConsumidorProductoIdRoute: ConsumidorProductoIdRoute,
  ConsumidorProductorSlugRoute: ConsumidorProductorSlugRoute,
  DistribuidorEntregaIdRoute: DistribuidorEntregaIdRoute,
  DistribuidorRecoleccionKeyRoute: DistribuidorRecoleccionKeyRoute,
  ProductorPedidoIdRoute: ProductorPedidoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
